### ISSUE TITLE
Outdated particles? (1.20.6)

### ISSUE THREAD

**Issue by NO-UUID** [BentoBoxWorld/TwerkingForTrees#36]
### Expected behavior

I think the error is due to Particle.SPELL being removed/renamed

### Observed/Actual behavior

```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event PlayerToggleSprintEvent to BentoBox v2.4.2-SNAPSHOT-b2664
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2605)
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:46)
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:18)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1519)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1496)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1419)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1385)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchFieldError: Class org.bukkit.Particle does not have member field 'org.bukkit.Particle SPELL'
	at world.bentobox.twerk.listeners.TreeGrowListener.lambda$twerk$16(TreeGrowListener.java:274)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at world.bentobox.twerk.listeners.TreeGrowListener.twerk(TreeGrowListener.java:257)
	at world.bentobox.twerk.listeners.TreeGrowListener.onSprint(TreeGrowListener.java:252)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor930.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	... 19 more
```

### Steps/models to reproduce

N/A

### BentoBox version

> bbox version
[22:12:34 INFO]: Running PAPER 1.20.6.
[22:12:34 INFO]: (1.20.6-DEV-631307b (MC: 1.20.6))
[22:12:34 INFO]: BentoBox version: 2.4.2-SNAPSHOT-b2664
[22:12:34 INFO]: Database: JSON
[22:12:34 INFO]: Loaded Game Worlds:
[22:12:34 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[22:12:34 INFO]: Loaded Addons:
[22:12:34 INFO]: Bank 1.8.0-SNAPSHOT-b94 (ENABLED)
[22:12:34 INFO]: Biomes 2.2.0-SNAPSHOT-b268 (ENABLED)
[22:12:34 INFO]: Border 4.3.0-SNAPSHOT-b205 (ENABLED)
[22:12:34 INFO]: BSkyBlock 1.18.0 (ENABLED)
[22:12:34 INFO]: CauldronWitchery 2.1.0-SNAPSHOT-#64 (ENABLED)
[22:12:34 INFO]: Challenges 1.3.0-SNAPSHOT-b550 (ENABLED)
[22:12:34 INFO]: CheckMeOut 1.2.0-SNAPSHOT-b97 (ENABLED)
[22:12:34 INFO]: ControlPanel 1.13.1 (ENABLED)
[22:12:34 INFO]: DimensionalTrees 1.7.0 (ENABLED)
[22:12:34 INFO]: ExtraMobs 1.13 (ENABLED)
[22:12:34 INFO]: IslandFly 1.12.0 (ENABLED)
[22:12:34 INFO]: Likes 2.4.0-SNAPSHOT-b106 (ENABLED)
[22:12:34 INFO]: MagicCobblestoneGenerator 2.5.2-SNAPSHOT-b277 (ENABLED)
[22:12:34 INFO]: TwerkingForTrees 1.5.1 (ENABLED)
[22:12:34 INFO]: Warps 1.15.1-SNAPSHOT-b368 (ENABLED)

**Comment by tastybento** [comment]
Thanks for the report!
